#!/bin/bash
# kairosdb-perf daemon
# chkconfig: 345 20 80
# description: KairosDB performance benchmark/monitor
# processname: kairosdb-perf

DAEMON=kairosdb-perf
DAEMONOPTS="-d"
DAEMON_PATH=$(dirname $(which $DAEMON))

NAME=kairosdb-perf
DESC="KairosDB performance benchmark/monitor"
LOGFILE="/var/log/$NAME.log"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

if [ "$EUID" -ne 0 ]
	then echo "service must run as root"
	exit
fi

case "$1" in
	start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	PID=`$DAEMON $DAEMONOPTS >> $LOGFILE 2>&1 & echo $!`
	if [ -z $PID ]; then
		printf "%s\n" "Fail"
	else
		echo $PID > $PIDFILE
		printf "%s\n" "Ok"
	fi
	;;
	status)
	printf "%-50s" "Checking $NAME..."
	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
			printf "%s\n" "Process dead but pidfile exists"
		else
			echo "Running"
		fi
	else
		printf "%s\n" "Service not running"
	fi
	;;
	stop)
	printf "%-50s" "Stopping $NAME"
	PID=`cat $PIDFILE`
	cd $DAEMON_PATH
	if [ -f $PIDFILE ]; then
		kill -HUP $PID
		printf "%s\n" "Ok"
		rm -f $PIDFILE
	else
		printf "%s\n" "pidfile not found"
	fi
	;;

	restart)
	$0 stop
	$0 start
	;;

	*)
	echo "Usage: $0 {status|start|stop|restart}"
	exit 1
esac
